<a href="https://colab.research.google.com/github/EduardoMedeiros2003/colab-com-python-/blob/main/Atividade_Pr%C3%A1tica_Gastos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a prática do K-means


In [ ]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 38.6 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd

# K-means

## Gastos totais de uma empresa com o passar dos anos

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
x=[ 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050]
y=[10000, 12000, 29000, 18500, 90000, 95000, 20000, 21000, 30000, 59000, 41000, 51000, 70000, 50000, 65000]

base do gráfico

In [ ]:
grafico = px.scatter(x = x, y = y)
grafico.show()

In [ ]:
base_gastos = np.array([[2014, 97637], [2032, 42347], [2002, 29652], [2028, 15197], [2007, 50127], [2047, 35820], [1985, 18021], [2017, 49811], [2026, 15888], [2046, 73323], [1994, 75321], [2031, 44140], [1990, 41630], [1987, 64703]])

fazendo base dos dados

In [ ]:
base_gastos

array([[ 2014, 97637],
       [ 2032, 42347],
       [ 2002, 29652],
       [ 2028, 15197],
       [ 2007, 50127],
       [ 2047, 35820],
       [ 1985, 18021],
       [ 2017, 49811],
       [ 2026, 15888],
       [ 2046, 73323],
       [ 1994, 75321],
       [ 2031, 44140],
       [ 1990, 41630],
       [ 1987, 64703]])

In [ ]:
scaler_gastos = StandardScaler()
base_gastos = scaler_gastos.fit_transform(base_gastos)

mudando a base dos dados para que o k-meanes entenda melhor

In [ ]:
base_gastos

array([[-0.03507239,  2.1735671 ],
       [ 0.84875193, -0.18514451],
       [-0.62428861, -0.72672244],
       [ 0.65234653, -1.34338326],
       [-0.37878186,  0.14675595],
       [ 1.58527221, -0.46359108],
       [-1.45901159, -1.22290936],
       [ 0.11223166,  0.13327516],
       [ 0.55414383, -1.31390469],
       [ 1.53617086,  1.13631418],
       [-1.01709943,  1.22155031],
       [ 0.79965058, -0.10865383],
       [-1.21350483, -0.21573225],
       [-1.36080889,  0.76857871]])

In [ ]:
kmeans_gastos = KMeans(n_clusters=6)
kmeans_gastos.fit(base_gastos)

KMeans(n_clusters=6)

In [ ]:
centroides = kmeans_gastos.cluster_centers_
centroides

array([[-0.03507239,  2.1735671 ],
       [ 1.1924614 ,  0.09473119],
       [-1.45901159, -1.22290936],
       [-1.18895416,  0.99506451],
       [ 0.60324518, -1.32864397],
       [-0.52608591, -0.1656059 ]])

achando onde está os centroides

In [ ]:
scaler_gastos.inverse_transform(kmeans_gastos.cluster_centers_)

array([[ 2014. , 97637. ],
       [ 2039. , 48907.5],
       [ 1985. , 18021. ],
       [ 1990.5, 70012. ],
       [ 2027. , 15542.5],
       [ 2004. , 42805. ]])

In [ ]:
rotulos = kmeans_gastos.labels_
rotulos

array([0, 1, 5, 4, 5, 1, 2, 5, 4, 1, 3, 1, 5, 3], dtype=int32)

In [ ]:
grafico1 = px.scatter(x=base_gastos[:, 0], y=base_gastos[:, 1], color=rotulos)
grafico2 = px.scatter(
    x=centroides[:, 0],
    y=centroides[:, 1],
    color=list(range(len(centroides))),
    size=[12] * len(centroides)
)
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()


In [ ]:
x_clusters = np.array([1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050])
y_clusters = np.array([10000, 12000, 29000, 18500, 90000, 95000, 20000, 21000, 30000, 59000, 41000, 51000, 70000, 50000, 65000])
rotulos = ["Cluster 1", "Cluster 2", "Cluster 1", "Cluster 3", "Cluster 2", "Cluster 3", "Cluster 1", "Cluster 2",
           "Cluster 3", "Cluster 1", "Cluster 2", "Cluster 3", "Cluster 1", "Cluster 2", "Cluster 3"]

In [ ]:
centroides = {
    "x": [1988, 2003, 2028],
    "y": [15000, 55000, 45000],
    "Cluster": ["Cluster 1", "Cluster 2", "Cluster 3"],
    "Tipo": ["Centróide"] * 3
}


In [ ]:
df_clusters = pd.DataFrame({"x": x_clusters, "y": y_clusters, "Cluster": rotulos, "Tipo": ["Ponto"] * len(x_clusters)})
df_centroides = pd.DataFrame(centroides)
df_final = pd.concat([df_clusters, df_centroides])


In [ ]:
grafico3 = px.scatter(
    df_final,
    x="x",
    y="y",
    color="Cluster",      # Cores por cluster
    symbol="Tipo",        # Diferenciação entre Ponto e Centróide
    size=df_final["Tipo"].apply(lambda t: 20 if t == "Centróide" else 10),  # Centrôides maiores
    labels={"x": "Anos", "y": "Gastos"},
    title="Gastos e Clusters com Centróides"
)

In [ ]:
grafico3.show()

In [ ]:
x_clusters = np.array([1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030, 2035, 2040, 2045, 2050])
y_clusters = np.array([10000, 12000, 29000, 18500, 90000, 95000, 20000, 21000, 30000, 59000, 41000, 51000, 70000, 50000, 65000])
rotulos = [
    "Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4",
    "Cluster 5", "Cluster 6", "Cluster 1", "Cluster 2",
    "Cluster 3", "Cluster 4", "Cluster 5", "Cluster 6",
    "Cluster 1", "Cluster 2", "Cluster 3"
]

In [ ]:
centroides = {
    "x": [1987, 1992, 2000, 2010, 2025, 2035],
    "y": [15000, 25000, 45000, 60000, 75000, 85000],
    "Cluster": ["Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Cluster 5", "Cluster 6"],
    "Tipo": ["Centróide"] * 6
}

In [ ]:
df_clusters = pd.DataFrame({"x": x_clusters, "y": y_clusters, "Cluster": rotulos, "Tipo": ["Ponto"] * len(x_clusters)})
df_centroides = pd.DataFrame(centroides)
df_final = pd.concat([df_clusters, df_centroides])

In [ ]:
grafico3 = px.scatter(
    df_final,
    x="x",
    y="y",
    color="Cluster",      # Cores por cluster
    symbol="Tipo",        # Diferenciação entre Ponto e Centróide
    size=df_final["Tipo"].apply(lambda t: 20 if t == "Centróide" else 10),  # Centróides maiores
    labels={"x": "Anos", "y": "Gastos"},
    title="Gastos e Clusters com 6 Centróides"
)

In [ ]:
grafico3.show()